# -*- coding: utf-8 -*-
"""DataScience.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4JMz2NpSEL6vnELdaMbvXLt9QHfsOhf
"""

import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")

df.head()

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()

clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max()

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df.loc[43]

#highest mid-career salary
clean_df['Undergraduate Major'].loc[clean_df['Mid-Career 90th Percentile Salary'].idxmax()]

#lowest starting salary
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

#Lowest mid-career salary
clean_df['Undergraduate Major'].loc[clean_df['Mid-Career 90th Percentile Salary'].idxmin()]

clean_df['Undergraduate Major'].loc[clean_df['Mid-Career Median Salary'].idxmin()]

clean_df['Mid-Career Median Salary'].loc[clean_df['Mid-Career Median Salary'].idxmin()]

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

#difference between 10th and 90th percent, lower difference is lower risk
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

low_risk

#top five highest mid-career
highest_90_at_10 = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_90_at_10[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

#highest risk/spread
high_risk = clean_df.sort_values('Spread', ascending = False)
high_risk[['Undergraduate Major', 'Spread']].head()

#highest risk/spread
highest_median_at_10 = clean_df.sort_values('Mid-Career Median Salary', ascending = False)
highest_median_at_10[['Undergraduate Major', 'Mid-Career Median Salary']].head()

clean_df.groupby('Group').count()

clean_df.groupby('Group').mean()

pd.options.display.float_format = '{:,.2f}'.format

